#!/usr/bin/env python

# Prof. Ira Woodring
# 11/14/2018
# CIS 343

from front.FrontEnd import FrontEnd
from player.Player import Player
from curses import wrapper

def main():
	player = Player()
	front_end = FrontEnd(player)

if __name__ == "__main__":
	main()
